FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    bash \
    curl \
    wget \
    bzip2 \
    qemu-system-x86 \
    qemu-utils \
    ovmf \
    novnc \
    websockify \
    tini \
    procps \
    net-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -d /home/container -s /bin/bash container

WORKDIR /home/container

USER container

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/bin/tini", "-s", "--"]
CMD ["/bin/bash"]
